# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.2 y modificado mediante edición de código posterior
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Program: class_canvas1.py -> Create the initial canvas
# Developed by: Ligdamis A. Gutiérrez E. PhD.
# Seismic Analysis System
# Andalusian Institute of Geophysics
# Science Faculty
# Granada University, (Ugr), Spain, 2023


import sys
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar

from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox
from PyQt5.QtWidgets import QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets

# Import Figure Object from Matplotlib
from matplotlib.figure import Figure

import matplotlib.pyplot as plt
import matplotlib.cbook as cbook

# Class to present the FigureCanvas Widget
class MplCanvas11(FigureCanvas):
    def __init__(self):
        # Matplotlib Figure and Axis format
        self.fig = Figure(facecolor = "#bfc4c8")
        #self.axes = self.fig.add_subplot(111)
        # Canvas initialization
        super(MplCanvas11, self).__init__(self.fig)
        FigureCanvas.__init__(self, self.fig)
        FigureCanvas.updateGeometry(self)

class MatplotlibWidget11_sin(QtWidgets.QWidget):
    """  El Widget es definido en QtDesigner """
    def __init__(self, parent = None):

        # Initialization of Qt MainWindow Widget
        QtWidgets.QWidget.__init__(self, parent)
        # Matplotlib Widget Canvas Callout (above)
        self.canvas = MplCanvas11()
        # Create a horizontal Box layout
        self.vbl = QtWidgets.QVBoxLayout()

        # Add the widget to the layout to the horizontal box
        self.vbl.addWidget(self.canvas)
        # Configure the layout for the horizontal th box
        self.setLayout(self.vbl)


#print("OK")
